### ISSUE TITLE
Get-PCInvoice -all doesn't work after Add-PCAuthentication execute with sucess

### ISSUE THREAD

**Issue by JuanFaustino** [Microsoft/PartnerCenterPowerShellModule#29]
After run Add-PCAuthentication with success, I try Get-PCInvoice -all and I get following error:
Method invocation failed because [System.Management.Automation.PSCustomObject] does not contain a method named 'Substring'.
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.9\src\PartnerCenterInvoice.psm1:58 char:9
+         $obj += $response.Substring(1) | ConvertFrom-Json
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Substring:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

**Comment by qbihay** [comment]
Same issue. I edit the psm1 file to add the debug and verbose param. 

VERBOSE: GET https://api.partnercenter.microsoft.com/v1/invoices/summary with 0-byte payload
VERBOSE: received 1034-byte response of content type application/json; charset=utf-8
Method invocation failed because [System.Management.Automation.PSCustomObject] does not contain a method named 'Substring'.

At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.10\PartnerCenterInvoice.psm1:37 char:9
+         $obj += $response.Substring(1) | ConvertFrom-Json
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Substring:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

**Comment by qbihay** [comment]
@JuanFaustino , you can edit the PartnerCenterInvoice.psm1 like that 
   function Private:Get-AllInvoicesInner($satoken)
    {
        $obj = @()
        $url = "https://api.partnercenter.microsoft.com/v1/invoices"
        $headers = @{Authorization="Bearer $satoken"}

        $response = Invoke-RestMethod -Uri $url -Headers $headers -ContentType "application/json" -Method "GET" #-Debug -Verbose
	
		$response2 = $response.items
		$obj = $response2 
		return (_formatResult -obj $obj -type "Invoice") 
    }

It works for me with the 0.9.0.10 module

**Comment by JuanFaustino** [comment]
qbihay, well done. It works for me too.
