### ISSUE TITLE
Cannot login to PartnerCenter for German Cloud ;(

### ISSUE THREAD

**Issue by dennings** [Microsoft/PartnerCenterPowerShellModule#44]
Cannot login to PartnerCenter for German Cloud ;(

Can someone implement that? Please!

**Comment by isaiahwilliams** [comment]
Hi @dennings, thank you for opening this issue. With the current design the module does not support the sovereign clouds. Right now we are in the process of planning changes that will make it work with US Government, Germany, and China. I will this issue open until we have implemented the appropriate changes.

**Comment by isaiahwilliams** [comment]
Hi @dennings, 

We just published a new pre-release version of a new Partner Center PowerShell module that has support for the German cloud. You can find more details about this version at https://github.com/Microsoft/Partner-Center-PowerShell. If you have an opportunity it would be great to get your feedback on the new module.

Since the new version has support for this feature I will be closing this issue now. If you encounter any issue with the new version please open an issue using the appropriate issue tracker.
